spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB
      location: ${java.io.tmpdir}/servbyte


app:
  jwt-config:
    secret: serve
    expiration-time: 480000
  upload-config:
    base: ${java.io.tmpdir}servbyte
  payment-config:
    url: https://api.paystack.co/transaction/initialize
    authorization: sk_test_fecc8b2a92aaef67c08a43a23332275a9989ea42
